# Generated by Django 5.0.6 on 2024-06-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_baseuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
