# Generated by Django 5.0.6 on 2024-06-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_inventory_delete_inventoryi'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='map_url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
