# Generated by Django 5.0.6 on 2024-06-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospital_map_url_alter_inventory_is_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
