# Generated by Django 5.0.6 on 2024-06-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_donationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
